package com.example.nativewebrequestdemo;

import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;

public interface TestController {
    @GetMapping(path = "/test")
    default ResponseEntity<String> _get() {
        // The @GetMapping is here. The user implements only the non-underscore method.
        return get();
    }

    default ResponseEntity<String> get() {
        // A stub generated by OpenAPI
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }
}
